import type { FeaturesSchema } from "../schemas/options/features.schema";
import type { OptionsSchema } from "../schemas/options/options.schema";

export const optionsSeeder: (Omit<OptionsSchema, "id"> & {
    features: Omit<FeaturesSchema, "id" | "option_id">[];
})[] = [
    {
        name: "Talla",
        type: 1,
        features: [
            { value: "XXXS", description: "Extra Extra Extra Small" },
            { value: "XXS", description: "Extra Extra Small" },
            { value: "XS", description: "Extra Small" },
            { value: "S", description: "Small" },
            { value: "M", description: "Medium" },
            { value: "L", description: "Large" },
            { value: "XL", description: "Extra Large" },
            { value: "XXL", description: "Extra Extra large" },
            { value: "XXXL", description: "Extra Extra extra large" },
            { value: "4XL", description: "4 extra large" },
            { value: "5XL", description: "5 extra large" },
            { value: "6XL", description: "6 extra large" },
        ],
    },
    {
        name: "Color",
        type: 2,
        features: [
            { value: "#000000", description: "Negro" },
            { value: "#ffffff", description: "Blanco" },
            { value: "#800080", description: "Morado" },
            { value: "#ff0000", description: "Rojo" },
            { value: "#00ff00", description: "Verde" },
            { value: "#0000ff", description: "Azul" },
            { value: "#ffff00", description: "Amarillo" },
            { value: "#ffa500", description: "Naranja" },
            { value: "#ffc0cb", description: "Rosa" },
            { value: "#a52a2a", description: "Marrón" },
            { value: "#808080", description: "Gris" },
            { value: "#00ffff", description: "Cian" },
            { value: "#ff00ff", description: "Fucsia" },
            { value: "#008000", description: "Verde Oscuro" },
            { value: "#800000", description: "Granate" },
            { value: "#000080", description: "Azul Marino" },
            { value: "#ffd700", description: "Dorado" },
            { value: "#4b0082", description: "Índigo" },
            { value: "#f0e68c", description: "Caqui" },
            { value: "#ffd700", description: "Oro" },
            { value: "#87ceeb", description: "Celeste" },
        ],
    },
    {
        name: "Sexo",
        type: 1,
        features: [
            { value: "M", description: "Masculino" },
            { value: "F", description: "Femenino" },
        ],
    },
    {
        name: "Calzado",
        type: 1,
        features: [
            { value: "20", description: "20 EUR" },
            { value: "21", description: "21 EUR" },
            { value: "22", description: "22 EUR" },
            { value: "23", description: "23 EUR" },
            { value: "24", description: "24 EUR" },
            { value: "25", description: "25 EUR" },
            { value: "26", description: "26 EUR" },
            { value: "27", description: "27 EUR" },
            { value: "28", description: "28 EUR" },
            { value: "29", description: "29 EUR" },
            { value: "30", description: "30 EUR" },
            { value: "31", description: "31 EUR" },
            { value: "32", description: "32 EUR" },
            { value: "33", description: "33 EUR" },
            { value: "34", description: "34 EUR" },
            { value: "35", description: "35 EUR" },
            { value: "36", description: "36 EUR" },
            { value: "37", description: "37 EUR" },
            { value: "38", description: "38 EUR" },
            { value: "39", description: "39 EUR" },
            { value: "40", description: "40 EUR" },
            { value: "41", description: "41 EUR" },
            { value: "42", description: "42 EUR" },
            { value: "43", description: "43 EUR" },
            { value: "44", description: "44 EUR" },
            { value: "45", description: "45 EUR" },
            { value: "46", description: "46 EUR" },
            { value: "47", description: "47 EUR" },
            { value: "48", description: "48 EUR" },
            { value: "49", description: "49 EUR" },
            { value: "50", description: "50 EUR" },
        ],
    },
    {
        name: "Almacenamiento",
        type: 1,
        features: [
            { value: "16 GB", description: "16 GB" },
            { value: "32 GB", description: "32 GB" },
            { value: "64 GB", description: "64 GB" },
            { value: "128 GB", description: "128 GB" },
            { value: "256 GB", description: "256 GB" },
            { value: "512 GB", description: "512 GB" },
            { value: "1024 GB", description: "1 TB" },
            { value: "2048 GB", description: "2 TB" },
        ],
    },
    {
        name: "Memoria RAM",
        type: 1,
        features: [
            { value: "2 GB", description: "2 GB Ram" },
            { value: "4 GB", description: "4 GB Ram" },
            { value: "8 GB", description: "8 GB Ram" },
            { value: "16 GB", description: "16 GB Ram" },
            { value: "32 GB", description: "32 GB Ram" },
            { value: "64 GB", description: "64 GB Ram" },
            { value: "128 GB", description: "128 GB Ram" },
            { value: "256 GB", description: "256 GB Ram" },
            { value: "512 GB", description: "512 GB Ram" },
        ],
    },
];
