export const departmentsSeeder = [
	{ ubigeo: "01", name: "Amazonas", priceShipping: 0, enabled: true, days: 3 },
	{
		ubigeo: "02",
		name: "\u00c1ncash",
		priceShipping: 0,
		enabled: true,
		days: 3,
	},
	{
		ubigeo: "03",
		name: "Apur\u00edmac",
		priceShipping: 0,
		enabled: true,
		days: 3,
	},
	{ ubigeo: "04", name: "Arequipa", priceShipping: 0, enabled: true, days: 3 },
	{ ubigeo: "05", name: "Ayacucho", priceShipping: 0, enabled: true, days: 3 },
	{ ubigeo: "06", name: "Cajamarca", priceShipping: 0, enabled: true, days: 3 },
	{ ubigeo: "07", name: "Callao", priceShipping: 0, enabled: true, days: 3 },
	{ ubigeo: "08", name: "Cusco", priceShipping: 0, enabled: true, days: 3 },
	{
		ubigeo: "09",
		name: "Huancavelica",
		priceShipping: 0,
		enabled: true,
		days: 3,
	},
	{
		ubigeo: "10",
		name: "Hu\u00e1nuco",
		priceShipping: 0,
		enabled: true,
		days: 3,
	},
	{ ubigeo: "11", name: "Ica", priceShipping: 0, enabled: true, days: 3 },
	{
		ubigeo: "12",
		name: "Jun\u00edn",
		priceShipping: 0,
		enabled: true,
		days: 3,
	},
	{
		ubigeo: "13",
		name: "La Libertad",
		priceShipping: 0,
		enabled: true,
		days: 3,
	},
	{
		ubigeo: "14",
		name: "Lambayeque",
		priceShipping: 0,
		enabled: true,
		days: 3,
	},
	{ ubigeo: "15", name: "Lima", priceShipping: 0, enabled: true, days: 3 },
	{ ubigeo: "16", name: "Loreto", priceShipping: 0, enabled: true, days: 3 },
	{
		ubigeo: "17",
		name: "Madre de Dios",
		priceShipping: 0,
		enabled: true,
		days: 3,
	},
	{ ubigeo: "18", name: "Moquegua", priceShipping: 0, enabled: true, days: 3 },
	{ ubigeo: "19", name: "Pasco", priceShipping: 0, enabled: true, days: 3 },
	{ ubigeo: "20", name: "Piura", priceShipping: 0, enabled: true, days: 3 },
	{ ubigeo: "21", name: "Puno", priceShipping: 0, enabled: true, days: 3 },
	{
		ubigeo: "22",
		name: "San Mart\u00edn",
		priceShipping: 0,
		enabled: true,
		days: 3,
	},
	{ ubigeo: "23", name: "Tacna", priceShipping: 0, enabled: true, days: 3 },
	{ ubigeo: "24", name: "Tumbes", priceShipping: 0, enabled: true, days: 3 },
	{ ubigeo: "25", name: "Ucayali", priceShipping: 0, enabled: true, days: 3 },
];
